### ISSUE TITLE
angular.element(...).emailautocomplete is not a function

### ISSUE THREAD

**Issue by subratastack** [magnobiet/ng-email-autocomplete#1]
I'm just using the same code as provided in the demo but I'm getting **angular.element(...).emailautocomplete is not a function**. My angularjs version is 1.2.x

**Comment by magnobiet** [comment]
Hi @subratawebops, sorry for my delayed return.

I'am testing with Angular 1.2.27, but the error is: `TypeError: angular.merge is not a function`.

A new branch ([legacy](https://github.com/magnobiet/ng-email-autocomplete/tree/legacy)) has created to solving this issue on legacy Angular.js versions.
